### PR TITLE
Added extra_args option

### PR DESCRIPTION
**Pull request by zonito**
PR: https://github.com/digitalcuisine/grunt-mysql-dump/pull/12

I guess, that person is now inactive. please udpate with extra_args and merge this. this is great feature

### CODE REVIEW

**Comment by olance** [comment]
:+1: 
Thanks @zonito I didn't have much time to spend on this right now!

**Comment by zonito** [comment]
Thanks @olance

**Comment by zonito** [comment]
@olance, Can you please create a release including this?

**Comment by olance** [comment]
done!

**Comment by zonito** [comment]
Great! thanks

**Pull request merged**
